tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-surface": "#2b2f34",
                "inverse-primary": "#4d8efe",
                "error-container": "#fb5151",
                "surface-container": "#e4e8ef",
                "primary": "#0058bc",
                "surface-container-lowest": "#ffffff",
                "secondary-dim": "#005d24",
                "surface-container-high": "#dee3ea",
                "surface-bright": "#f4f7fc",
                "outline-variant": "#aaadb3",
                "secondary-fixed": "#86f898",
                "inverse-surface": "#0a0f13",
                "on-tertiary": "#ffefed",
                "error-dim": "#9f0519",
                "on-primary-container": "#00214f",
                "on-secondary": "#cfffcf",
                "on-error-container": "#570008",
                "tertiary-fixed-dim": "#ff7c6b",
                "surface-container-low": "#edf1f7",
                "on-primary": "#f0f2ff",
                "on-tertiary-container": "#690002",
                "on-error": "#ffefee",
                "surface": "#f4f7fc",
                "inverse-on-surface": "#999da3",
                "surface-tint": "#0058bc",
                "on-primary-fixed": "#000000",
                "on-secondary-fixed-variant": "#00682a",
                "on-surface-variant": "#585c61",
                "on-primary-fixed-variant": "#002a61",
                "secondary-fixed-dim": "#78e98b",
                "background": "#f4f7fc",
                "on-secondary-container": "#005d25",
                "surface-container-highest": "#d8dde5",
                "on-tertiary-fixed": "#3a0001",
                "tertiary-container": "#ff9384",
                "tertiary-dim": "#a30709",
                "surface-variant": "#d8dde5",
                "primary-container": "#6d9fff",
                "outline": "#73777c",
                "on-secondary-fixed": "#00481b",
                "on-background": "#2b2f34",
                "tertiary-fixed": "#ff9384",
                "tertiary": "#b41a14",
                "secondary-container": "#86f898",
                "primary-fixed": "#6d9fff",
                "primary-dim": "#004ca5",
                "error": "#b31b25",
                "primary-fixed-dim": "#5291ff",
                "secondary": "#006a2b",
                "on-tertiary-fixed-variant": "#7a0003",
                "surface-dim": "#cfd5dd"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
};
